version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "1323:1323"
    volumes:
      - ./backend:/api # バインド
    tty: true
    stdin_open: true