version: '3'

services:
    api:
        build: ./backend
        command: go run main.go
        container_name: (api)image-uploader
        ports:
            - "1323:1323"
        volumes: 
            - ./backend:/api # バインド